### ISSUE TITLE
Feature Request: Ability to cache Evernote content as notes and reminders in an Akonadi backend for KDE PIM integration.

### ISSUE THREAD

**Issue by timoc** [d1vanov/libquentier#160]
The KDE Akonadi framework has a QTbased abstraction for storing this kind of PIM information in a mysql/sqlite and pgsql backend for the KDE pim suite. My request is to allow libquentier to use this instead of sqlite as a backend.

**Comment by d1vanov** [comment]
Thank you for the suggestion but I definitely won't be doing this in any observable future. It might be a nice feature for KDE users as it would probably make libquentier's storage searchable and accessible to other apps from KDE suite but it won't benefit the users of other DEs. And I still have a lot of more important things to do around Quentier and libquentier even though with years I have less and less free time for these projects...

If someone else would like to do this, I'm not totally opposed to the idea. But then let's discuss the design before writing any code.
