### ISSUE TITLE
Spell checker inserts suggested word with '&' prefix

### ISSUE THREAD

**Issue by michaelkn** [d1vanov/libquentier#40]
Steps to reproduce: input a misspelled word and try to replace it using context menu.

**Comment by d1vanov** [comment]
This one and #42 should be fixed after commit [5e4fc24](https://github.com/d1vanov/libquentier/commit/5e4fc24d79380b45f20116d195189e6900017508) in branches [master](https://github.com/d1vanov/libquentier/commit/master) and [development](https://github.com/d1vanov/libquentier/commit/development). Also created d1vanov/quentier#155 to see if context menus on the app side are also affected by this.
